# Generated by Django 3.0.7 on 2020-06-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_publicshed',
            new_name='is_published',
        ),
    ]
